from collections.abc import Iterator
from typing import Any, Protocol, TypeVar, runtime_checkable

from redis.typing import KeyT


@runtime_checkable
class RawClientProtocol(Protocol):
    """Protocol defining client methods used by django-redis mixins.

    This protocol is satisfied by:
    - redis-py: Redis, RedisCluster
    - valkey-py: Valkey, ValkeyCluster

    It enables type-safe client parameter passing across different
    Redis/Valkey-compatible backends.
    """

    # Set operations
    def sadd(self, name: Any, *values: Any) -> int: ...
    def scard(self, name: Any) -> int: ...
    def sdiff(self, keys: Any, *args: Any) -> set: ...
    def sdiffstore(self, dest: Any, keys: Any, *args: Any) -> int: ...
    def sinter(self, keys: Any, *args: Any) -> set: ...
    def sinterstore(self, dest: Any, keys: Any, *args: Any) -> int: ...
    def sismember(self, name: Any, value: Any) -> bool: ...
    def smembers(self, name: Any) -> set: ...
    def smismember(self, name: Any, values: Any, *args: Any) -> list: ...
    def smove(self, src: Any, dst: Any, value: Any) -> bool: ...
    def spop(self, name: Any, count: int | None = None) -> Any: ...
    def srandmember(self, name: Any, number: int | None = None) -> Any: ...
    def srem(self, name: Any, *values: Any) -> int: ...
    def sscan(
        self,
        name: Any,
        cursor: int = 0,
        match: Any | None = None,
        count: int | None = None,
    ) -> tuple[int, list]: ...
    def sscan_iter(
        self,
        name: Any,
        match: Any | None = None,
        count: int | None = None,
    ) -> Iterator: ...
    def sunion(self, keys: Any, *args: Any) -> set: ...
    def sunionstore(self, dest: Any, keys: Any, *args: Any) -> int: ...

    # Hash operations
    def hset(
        self,
        name: Any,
        key: Any | None = None,
        value: Any | None = None,
        mapping: dict | None = None,
    ) -> int: ...
    def hdel(self, name: Any, *keys: Any) -> int: ...
    def hlen(self, name: Any) -> int: ...
    def hkeys(self, name: Any) -> list: ...
    def hexists(self, name: Any, key: Any) -> bool: ...
    def hget(self, name: Any, key: Any) -> Any: ...
    def hgetall(self, name: Any) -> dict: ...
    def hmget(self, name: Any, keys: Any, *args: Any) -> list: ...
    def hincrby(self, name: Any, key: Any, amount: int = 1) -> int: ...
    def hincrbyfloat(self, name: Any, key: Any, amount: float = 1.0) -> float: ...
    def hsetnx(self, name: Any, key: Any, value: Any) -> int: ...
    def hvals(self, name: Any) -> list: ...

    # List operations
    def lpush(self, name: Any, *values: Any) -> int: ...
    def rpush(self, name: Any, *values: Any) -> int: ...
    def lpop(self, name: Any, count: int | None = None) -> Any: ...
    def rpop(self, name: Any, count: int | None = None) -> Any: ...
    def lrange(self, name: Any, start: int, end: int) -> list: ...
    def lindex(self, name: Any, index: int) -> Any: ...
    def llen(self, name: Any) -> int: ...
    def lrem(self, name: Any, count: int, value: Any) -> int: ...
    def ltrim(self, name: Any, start: int, end: int) -> bool: ...
    def lset(self, name: Any, index: int, value: Any) -> bool: ...
    def linsert(self, name: Any, where: str, refvalue: Any, value: Any) -> int: ...
    def lpos(
        self,
        name: Any,
        value: Any,
        rank: int | None = None,
        count: int | None = None,
        maxlen: int | None = None,
    ) -> Any: ...
    def lmove(
        self,
        first_list: Any,
        second_list: Any,
        src: str = "LEFT",
        dest: str = "RIGHT",
    ) -> Any: ...
    def blpop(self, keys: Any, timeout: float = 0) -> Any: ...
    def brpop(self, keys: Any, timeout: float = 0) -> Any: ...
    def blmove(
        self,
        first_list: Any,
        second_list: Any,
        timeout: float,
        src: str = "LEFT",
        dest: str = "RIGHT",
    ) -> Any: ...

    # Sorted set operations
    def zadd(
        self,
        name: Any,
        mapping: Any,
        nx: bool = False,
        xx: bool = False,
        ch: bool = False,
        incr: bool = False,
        gt: bool = False,
        lt: bool = False,
    ) -> int: ...
    def zcard(self, name: Any) -> int: ...
    def zcount(self, name: Any, min: Any, max: Any) -> int: ...
    def zincrby(self, name: Any, amount: float, value: Any) -> float: ...
    def zpopmax(self, name: Any, count: int | None = None) -> list: ...
    def zpopmin(self, name: Any, count: int | None = None) -> list: ...
    def zrange(
        self,
        name: Any,
        start: int,
        end: int,
        desc: bool = False,
        withscores: bool = False,
        score_cast_func: type = float,
    ) -> list: ...
    def zrangebyscore(
        self,
        name: Any,
        min: Any,
        max: Any,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
        score_cast_func: type = float,
    ) -> list: ...
    def zrank(self, name: Any, value: Any) -> int | None: ...
    def zrem(self, name: Any, *values: Any) -> int: ...
    def zremrangebyscore(self, name: Any, min: Any, max: Any) -> int: ...
    def zrevrange(
        self,
        name: Any,
        start: int,
        end: int,
        withscores: bool = False,
        score_cast_func: type = float,
    ) -> list: ...
    def zrevrangebyscore(
        self,
        name: Any,
        max: Any,
        min: Any,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
        score_cast_func: type = float,
    ) -> list: ...
    def zscore(self, name: Any, value: Any) -> float | None: ...
    def zrevrank(self, name: Any, value: Any) -> int | None: ...
    def zmscore(self, name: Any, keys: Any, *args: Any) -> list: ...
    def zremrangebyrank(self, name: Any, min: int, max: int) -> int: ...


# TypeVar for Redis client types, bounded by our protocol
# This ensures type safety while supporting Redis, RedisCluster, and future Valkey
RawClientT = TypeVar("RawClientT", bound=RawClientProtocol)


class ClientProtocol(Protocol):
    """Protocol for client methods required by mixins.

    Any class using django-redis mixins must implement these methods.
    """

    def make_key(
        self,
        key: KeyT,
        version: int | None = None,
        prefix: str | None = None,
    ) -> KeyT:
        """Create a cache key with optional version and prefix."""
        ...

    def encode(self, value: Any) -> bytes | int:
        """Encode a value for storage in Redis."""
        ...

    def decode(self, value: bytes | int) -> Any:
        """Decode a value retrieved from Redis."""
        ...

    def get_client(self, write: bool = False) -> Any:
        """Get a Redis client instance for read or write operations."""
        ...

    def _has_compression_enabled(self) -> bool:
        """Check if compression is enabled for this client."""
        ...

    def _decode_iterable_result(
        self,
        result: Any,
        convert_to_set: bool = True,
    ) -> list[Any] | set[Any] | None | Any:
        """Decode an iterable result from Redis."""
        ...
